const Images = {
  background: "./contents/images/backgroundFlorest.png",
  floorWood: "./contents/images/floor-wood.png",
  floorRocks: "./contents/images/floor-rocks.png",
  floorMosaic: "./contents/images/floor-mosaic.png",
  floorSand: "./contents/images/floor-sand.png",
  hole: "./contents/images/floor-hole.png",
  dirt: "./contents/images/floor-dirt.png",
  verticalStonelWall: "./contents/images/vertical-stone-wall.png",
  horizontalStonelWall: "./contents/images/horizontal-stone-wall.png",
  verticalStoneOpenWall: "./contents/images/vertical-stone-open-wall.png",
  horizontalStoneOpenWall: "./contents/images/horizontal-stone-open-wall.png",
  openDoor: "./contents/images/open-door.png",
  closeDoor: "./contents/images/close-door.png",
  soundIcon: "./contents/images/sound-icon.png",
  enemyPortal: "./contents/images/enemy-portal.png",
  menuIcon: "./contents/images/menuIcon.png",
  chest: {
    red: {
      open: "./contents/images/chest-red-opened.png",
      close: "./contents/images/chest-red-closed.png",
    },
    blue: {
      open: "./contents/images/chest-blue-opened.png",
      close: "./contents/images/chest-blue-closed.png",
    },
    green: {
      open: "./contents/images/chest-green-opened.png",
      close: "./contents/images/chest-green-closed.png",
    },
    brown: {
      open: "./contents/images/chest-brown-opened.png",
      close: "./contents/images/chest-brown-closed.png",
    },
  },
  pins: {
    blue: "./contents/images/characters/bluePin.png",
    red: "./contents/images/characters/redPin.png",
    green: "./contents/images/characters/greenPin.png",
    yellow: "./contents/images/characters/yellowPin.png",
    black: "./contents/images/characters/blackPin.png",
    white: "./contents/images/characters/whitePin.png",
  },
  arrow: {
    grey: {
      left: "./contents/images/leftGreyArrow.png",
      right: "./contents/images/rightGreyArrow.png",
      top: "./contents/images/topGreyArrow.png",
      bottom: "./contents/images/bottomGreyArrow.png",
    },
    black: {
      left: "./contents/images/leftBlackArrow.png",
      right: "./contents/images/rightBlackArrow.png",
      top: "./contents/images/topBlackArrow.png",
      bottom: "./contents/images/bottomBlackArrow.png",
    },
  },
  player: {
    human: "./contents/images/characters/knight.png",
    archer: "./contents/images/characters/archer.png",
    elf: "./contents/images/characters/ranger.png",
    mage: "./contents/images/characters/mage.png",
    thief: "./contents/images/characters/thief.png",
    dwarf: "./contents/images/characters/barbarian.png",
  },
  enemy: {
    orc: "./contents/images/characters/orc.png",
    zombie: "./contents/images/characters/zombie.png",
    beast: "./contents/images/characters/beast.png",
    skeleton: "./contents/images/characters/skeleton.png",
  },
  weapon: {
    dagger: "./contents/images/weapons/dagger.png",
    sword: "./contents/images/weapons/sword-normal.png",
    swordLong: "./contents/images/weapons/sword-long.png",
    swordTwoHands: "./contents/images/weapons/sword-two-hands.png",
    spear: "./contents/images/weapons/spear.png",
    hammer: "./contents/images/weapons/hammer.png",
    axe: "./contents/images/weapons/axe-normal.png",
    axeTwoHands: "./contents/images/weapons/axe-two-hands.png",
    crossbow: "./contents/images/weapons/crossbow.png",
    bow: "./contents/images/weapons/bow-normal.png",
    bowLong: "./contents/images/weapons/bow-long.png",
    staffNonElemental: "./contents/images/weapons/staf-non-elemental.png",
    staffLight: "./contents/images/weapons/staf-light.png",
    staffDarkness: "./contents/images/weapons/staf-darkness.png",
    staffWater: "./contents/images/weapons/staf-water.png",
    staffFire: "./contents/images/weapons/staf-fire.png",
    staffEarth: "./contents/images/weapons/staf-earth.png",
    staffAir: "./contents/images/weapons/staf-air.png",
    staffTwoHands: "./contents/images/weapons/staf-long.png",
    shieldWeak: "./contents/images/weapons/shield-wood.png",
    shieldMid: "./contents/images/weapons/shield-mid.png",
    shieldStrong: "./contents/images/weapons/shield-steel.png",
    armourLeather: "./contents/images/weapons/armour-leather.png",
    armourMithril: "./contents/images/weapons/armour-mithril.png",
  },
};

export default Images;
