// precision 0: All
// precision 1: Sword
// precision 2: Axe
// precision 3: Bow
// precision 4: Staff

import Images from "./Images";

const WeaponData = {
  dagger: {
    name: "",
    description: "",
    image: Images.weapon.dagger,
    oneHand: true,
    range: 1,
    type: "sword",
    strenth: 1,
    chance: 3,
    element: "none",
    precision: 0,
  },
  sword: {
    name: "Espada de Cavaleiro",
    description: "",
    image: Images.weapon.sword,
    oneHand: true,
    range: 1,
    type: "sword",
    strenth: 1,
    chance: 3,
    element: "none",
    precision: 0,
  },
  swordLong: {
    name: "",
    description: "",
    image: Images.weapon.swordLong,
    oneHand: true,
    range: 1,
    type: "sword",
    strenth: 1,
    chance: 4,
    element: "none",
    precision: 0,
  },
  swordTwoHands: {
    name: "",
    description: "",
    image: Images.weapon.swordTwoHands,
    oneHand: false,
    range: 1,
    type: "sword",
    strenth: 2,
    chance: 4,
    element: "none",
    precision: 1,
  },
  spear: {
    name: "",
    description: "",
    image: Images.weapon.spear,
    oneHand: false,
    range: 2,
    type: "sword",
    strenth: 1,
    chance: 4,
    element: "none",
    precision: 1,
  },
  hammer: {
    name: "",
    description: "",
    image: Images.weapon.hammer,
    oneHand: true,
    range: 1,
    type: "axe",
    strenth: 1,
    chance: 3,
    element: "none",
    precision: 0,
  },
  axe: {
    name: "",
    description: "",
    image: Images.weapon.axe,
    oneHand: true,
    range: 1,
    type: "axe",
    strenth: 1,
    chance: 4,
    element: "none",
    precision: 0,
  },
  axeTwoHands: {
    name: "",
    description: "",
    image: Images.weapon.axeTwoHands,
    oneHand: false,
    range: 1,
    type: "axe",
    strenth: 2,
    chance: 4,
    element: "none",
    precision: 2,
  },
  crossbow: {
    name: "",
    description: "",
    image: Images.weapon.crossbow,
    oneHand: true,
    range: 2,
    type: "bow",
    strenth: 1,
    chance: 3,
    element: "none",
    precision: 0,
  },
  bow: {
    name: "",
    description: "",
    image: Images.weapon.bow,
    oneHand: false,
    range: 2,
    type: "bow",
    strenth: 1,
    chance: 4,
    element: "none",
    precision: 3,
  },
  bowLong: {
    name: "Arco de Apolo",
    description: "",
    image: Images.weapon.bowLong,
    oneHand: false,
    range: 3,
    type: "bow",
    strenth: 2,
    chance: 4,
    element: "none",
    precision: 3,
  },
  staffNonElemental: {
    name: "Cajado de Aprendiz",
    description: "",
    image: Images.weapon.staffNonElemental,
    oneHand: true,
    range: 2,
    type: "staff",
    strenth: 1,
    chance: 3,
    element: "none",
    precision: 4,
  },
  staffLight: {
    name: "",
    description: "",
    image: Images.weapon.staffLight,
    oneHand: true,
    range: 2,
    type: "staff",
    strenth: 1,
    chance: 3,
    element: "light",
    precision: 4,
  },
  staffDarkness: {
    name: "",
    description: "",
    image: Images.weapon.staffDarkness,
    oneHand: true,
    range: 2,
    type: "staff",
    strenth: 1,
    chance: 3,
    element: "darkness",
    precision: 4,
  },
  staffWater: {
    name: "",
    description: "",
    image: Images.weapon.staffWater,
    oneHand: true,
    range: 2,
    type: "staff",
    strenth: 1,
    chance: 3,
    element: "water",
    precision: 4,
  },
  staffFire: {
    name: "",
    description: "",
    image: Images.weapon.staffFire,
    oneHand: true,
    range: 2,
    type: "staff",
    strenth: 1,
    chance: 3,
    element: "fire",
    precision: 4,
  },
  staffEarth: {
    name: "",
    description: "",
    image: Images.weapon.staffEarth,
    oneHand: true,
    range: 2,
    type: "staff",
    strenth: 1,
    chance: 3,
    element: "earth",
    precision: 4,
  },
  staffAir: {
    name: "",
    description: "",
    image: Images.weapon.staffAir,
    oneHand: true,
    range: 2,
    type: "staff",
    strenth: 1,
    chance: 3,
    element: "air",
    precision: 4,
  },
  staffTwoHands: {
    name: "Cajado de Merlin",
    description: "",
    image: Images.weapon.staffTwoHands,
    oneHand: false,
    range: 3,
    type: "staff",
    strenth: 2,
    chance: 4,
    element: "random",
    precision: 4,
  },
  shieldWeak: {
    name: "",
    description: "",
    image: Images.weapon.shieldWeak,
    oneHand: true,
    range: 0,
    type: "shield",
    strenth: 1,
    chance: 2,
    element: "none",
    precision: 0,
  },
  shieldMid: {
    name: "",
    description: "",
    image: Images.weapon.shieldMid,
    oneHand: true,
    range: 0,
    type: "shield",
    strenth: 1,
    chance: 3,
    element: "none",
    precision: 0,
  },
  shieldStrong: {
    name: "",
    description: "",
    image: Images.weapon.shieldStrong,
    oneHand: true,
    range: 0,
    type: "shield",
    strenth: 1,
    chance: 4,
    element: "none",
    precision: 0,
  },
  armourLeather: {
    name: "",
    description: "",
    image: Images.weapon.armourLeather,
    oneHand: true,
    range: 0,
    type: "armour",
    strenth: 1,
    chance: 2,
    element: "none",
    precision: 0,
  },
  armourMithril: {
    name: "",
    description: "",
    image: Images.weapon.armourMithril,
    oneHand: true,
    range: 0,
    type: "armour",
    strenth: 1,
    chance: 3,
    element: "none",
    precision: 0,
  },
};

export default WeaponData;
